---
abstract: 'Ask or tell when certain types of tests should be run'
author:
  - 'Matthew Horsfall (alh) <WolfSage@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Settings
resources:
  homepage: https://github.com/wolfsage/Test-Settings
  repository: git://github.com/wolfsage/Test-Settings.git
version: 0.001
